LABEL_PATH = r"C:\Users\Dell\Documents\GitHub\blood_cell_detect\obj.names"
CFG_PATH = "../inputs/yolov3-custom.cfg"
WEIGHT_PATH = "../inputs/yolov3-custom_last.weights"
YOLO_PATH = "../"
LOG_FILES = "../Logs/"